services:
  scaler:
    image: fviolence/scaler:latest
    container_name: scaler
    privileged: true
    user: 0:0
    environment:
      - GPU_ACCEL=${GPU_ACCEL}
    volumes:
      - ${WATCH_DIRECTORY}:/watch_dir
    devices:
      ${DEVICES}
    restart: unless-stopped
